### ISSUE TITLE
tensorflow issue

### ISSUE THREAD

**Issue by Dantong0606** [aws-samples/training-llm-on-sagemaker-for-multiple-nodes-with-deepspeed#2]
I cloned the repo and copied anything in a sagemaker notebook instance `ml.m5.large`, and then ran the `DeepSpeed-Flan-T5-on-Sagemaker-multiple-nodes.ipynb`, the sagemake training job failed with `ModuleNotFoundError: No module named 'tensorflow' error.` The following is the detailed traceback

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/smdebug-1.0.22b20220929-py3.8.egg/smdebug/core/utils.py", line 48, in <module>
    import smdistributed.modelparallel.tensorflow as smp
  File "/opt/conda/lib/python3.8/site-packages/smdistributed/modelparallel/tensorflow/__init__.py", line 3, in <module>
    from smdistributed.modelparallel.tensorflow.comm import *
  File "/opt/conda/lib/python3.8/site-packages/smdistributed/modelparallel/tensorflow/comm.py", line 4, in <module>
    from smdistributed.modelparallel.tensorflow.state_mod import state
  File "/opt/conda/lib/python3.8/site-packages/smdistributed/modelparallel/tensorflow/state_mod.py", line 6, in <module>
    import tensorflow as tf
```

I then added `tensorflow==2.12.0` in the requirement.txt, and re-ran the `DeepSpeed-Flan-T5-on-Sagemaker-multiple-nodes.ipynb`, the sagemaker training job failed with 
`terminate called after throwing an instance of 'std::runtime_error'  what():  random_device could not be read | terminate called after throwing an instance of 'std::runtime_error' what(): random_device could not be read`

Do you know how to fix it?

Thanks!

**Comment by AnuragNagare** [comment]
1] Check Dependencies:
Make sure you have the correct versions of dependencies for the notebook you're running. 
2] TensorFlow Compatibility:
The error you initially encountered, ModuleNotFoundError: No module named 'tensorflow', indicates that TensorFlow was not installed. Adding tensorflow==2.12.0 to the requirements.txt was a step in the right direction, but make sure that this version is compatible with the other libraries you're using.
3] Random Device Error:
The error random_device could not be read might be due to an issue with your environment rather than your code. This error is often related to insufficient permissions to access the system's random device.
4] Error Details:
The error message mentions terminate called after throwing an instance of 'std::runtime_error' what(): random_device could not be read. This seems to be related to random number generation in C++ code

**Comment by yuhuiaws** [comment]
Maybe the built-in SageMaker Huggingface training container had some changes, it will result in the failure about deepspeed training on SageMaker. The workaroud is as following:
a. Change the requirements.txt as following:
     transformers==4.28.1
     datasets
     sentencepiece
     accelerate
     evaluate
     deepspeed==0.9.2
     ninja
     rouge-score
     bitsandbytes
b. Change SageMaker huggingface training container to SageMaker pytorch 1.12 training container:
from sagemaker.pytorch import PyTorch
estimator = PyTorch(entry_point='start.py',
             source_dir           = 'src', 
             instance_type='ml.p4d.24xlarge',
             instance_count=2,
             role=role,
             base_job_name = job_name, 
             keep_alive_period_in_seconds=1800,
             framework_version='1.12.0',
             py_version='py38',
             environment = environment,
             disable_profiler=True,
             debugger_hook_config=False)

And the above workaround works well.
